services:
  - type: web
    plan: free
    name: mconfige
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
